### ISSUE TITLE
Create the bubble 15 minutes before the start datetime

### ISSUE THREAD

**Issue by Bricklou** [HybridPlanner/backend#46]
Use the SchedulerService
Update the Meeting Model to store the `bubbleId?` after it has been created. Remember to run `npx prisma migrate dev` to generate the migration.

**Comment by Augustin68** [comment]
## TODO :

- [ ] Update Meeting model with `bubbleId?`
- [ ] Add a cron job to check every minutes if new bubbles need to be started
- [ ] In the cron job, get all the meetings that start between now and +15min. If they do not have any `bubbleId ` yet, create the bubble and add the bubbleId.
